version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: springcourse
      MYSQL_DATABASE: todos
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
    volumes:
      - '/docker/volume/mysql:/var/lib/mysql'
      - '/data /docker-entrypoint-initdb.d'
      - '/config /etc/mysql/conf.d'
