version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: 'springcourse'
      MYSQL_DATABASE: my_db333
      MYSQL_USER: 'bestuser'
      MYSQL_PASSWORD: 'bestuser'

    volumes:

      - '/data/2.sql:/docker-entrypoint-initdb.d/2.sql'



